name: run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24.0.x"
          elixir-version: "1.12.x"
      - run: mix deps.get
      - run: mix test
